"""caregiver URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
# Automaticaly added by Django manage.py
from django.contrib import admin
from django.urls import path
# Importing in order to be able to use include()
from django.conf.urls import include
# Importing in order to be able to use RedirectView and redirect base URL
from django.views.generic import RedirectView
# Importing to be able to use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

# Adding path to admin module -- automatic generated by Django manage.py
urlpatterns = [
    path('admin/', admin.site.urls),
]

# Adding path to catalog application
urlpatterns += [
    path('cg_catalog/', include('cg_catalog.urls')),
]

# Redirecting base URL to catalog application
urlpatterns += [
    path('', RedirectView.as_view(url='/cg_catalog/')),
]

# To be able to add url mapping to serve static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)